import type { ProtocolItem } from "../types";

export const defaultSleepProtocol: ProtocolItem[] = [
  // ── MORNING (timingAnchor: "wake") ────────────────────────────
  {
    id: "sleep-default-001",
    pillar: "sleep",
    name: "Morning Sunlight",
    description:
      "Get 10-30 min of sunlight within 30 min of waking. Sets your circadian clock via the suprachiasmatic nucleus, the most powerful zeitgeber for your sleep-wake cycle.",
    source: "default",
    timingAnchor: "wake",
    timingOffsetMinutes: 15,
    timeOfDay: "morning",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 1,
    isEnabled: true,
    icon: "☀️",
    recommendedBy: ["Huberman", "Attia"],
    evidenceNote:
      "Bright-light exposure in the first hour of waking advances the cortisol pulse and suppresses melatonin, anchoring the circadian phase. Even overcast outdoor light (~10,000 lux) is 10-50x brighter than indoor lighting.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-002",
    pillar: "sleep",
    name: "Cold Exposure",
    description:
      "1-3 min cold shower. Increases dopamine and cortisol at the right time of day, promoting alertness and reinforcing the morning cortisol peak.",
    source: "default",
    timingAnchor: "wake",
    timingOffsetMinutes: 30,
    timeOfDay: "morning",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 2,
    isEnabled: true,
    icon: "🧊",
    recommendedBy: ["Huberman"],
    evidenceNote:
      "Brief cold-water immersion triggers a sustained 200-300% increase in dopamine lasting several hours, along with norepinephrine release that supports wakefulness and mood.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-003",
    pillar: "sleep",
    name: "Delay Caffeine",
    description:
      "Wait 90-120 min after waking for caffeine. Lets adenosine clear naturally so you avoid an afternoon crash and don't mask residual sleep pressure.",
    source: "default",
    timingAnchor: "wake",
    timingOffsetMinutes: 90,
    timeOfDay: "morning",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 3,
    isEnabled: true,
    icon: "☕",
    recommendedBy: ["Huberman"],
    evidenceNote:
      "Adenosine accumulates during waking and is partly cleared during sleep. Consuming caffeine immediately blocks adenosine receptors before they naturally clear, leading to a stronger afternoon crash when the caffeine wears off.",
    createdAt: "2026-01-01T00:00:00Z",
  },

  // ── EVENING (timingAnchor: "bed") ─────────────────────────────
  {
    id: "sleep-default-004",
    pillar: "sleep",
    name: "Caffeine Cutoff",
    description:
      "No caffeine after this time. Caffeine has a half-life of 5-7 hours and disrupts deep sleep architecture even when you feel you can fall asleep.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -600,
    timeOfDay: "morning",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 4,
    isEnabled: true,
    icon: "⛔",
    recommendedBy: ["Walker", "Huberman"],
    evidenceNote:
      "Caffeine consumed 6 hours before bed reduced total sleep by over 1 hour in controlled studies. It selectively suppresses slow-wave (deep) sleep, even when subjective sleep quality feels unchanged.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-005",
    pillar: "sleep",
    name: "Last Meal",
    description:
      "Finish eating 3+ hours before bed. Reduces core temperature disruption from digestion, allowing the thermoregulatory drop needed for sleep onset.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -180,
    timeOfDay: "evening",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 5,
    isEnabled: true,
    icon: "🍽️",
    recommendedBy: ["Attia", "Huberman"],
    evidenceNote:
      "Late eating raises core body temperature via diet-induced thermogenesis. Since the body must drop ~1-1.5°C to initiate sleep, eating close to bedtime delays sleep onset and reduces sleep efficiency.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-006",
    pillar: "sleep",
    name: "Dim Lights",
    description:
      "Switch to warm, low-positioned lighting. Overhead bright light in the evening suppresses melatonin production by up to 50%.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -120,
    timeOfDay: "evening",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 6,
    isEnabled: true,
    icon: "🔅",
    recommendedBy: ["Huberman", "Walker"],
    evidenceNote:
      "Light viewed from below eye level (table lamps, candles) activates fewer melanopsin-containing retinal ganglion cells than overhead light, preserving melatonin onset. Warm-spectrum light (<3000K) has the least suppressive effect.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-007",
    pillar: "sleep",
    name: "Screens Off",
    description:
      "No screens or use blue-light blocking glasses. Blue light (460-480nm) is the most potent suppressor of melatonin secretion.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -60,
    timeOfDay: "evening",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 7,
    isEnabled: true,
    icon: "📱",
    recommendedBy: ["Walker", "Huberman"],
    evidenceNote:
      "Screen use before bed delays melatonin onset by an average of 1.5 hours. The cognitive stimulation from device content compounds the photobiological effect of the light itself.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-008",
    pillar: "sleep",
    name: "Cool Bedroom",
    description:
      "Set room to 65-68°F (18-20°C). Core body temperature must drop 1-1.5°C for sleep onset; a cool room facilitates this via peripheral vasodilation.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -30,
    timeOfDay: "night",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 8,
    isEnabled: true,
    icon: "❄️",
    recommendedBy: ["Walker", "Huberman", "Attia"],
    evidenceNote:
      "Ambient temperature is the most under-appreciated factor in sleep quality. A room temperature of 65-68°F allows heat to dissipate from the body's core through the hands and feet, triggering the hypothalamic sleep switch.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-009",
    pillar: "sleep",
    name: "Magnesium Supplement",
    description:
      "Take 200-400mg magnesium threonate or bisglycinate. These forms cross the blood-brain barrier and activate GABA pathways to promote relaxation.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -30,
    timeOfDay: "night",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 9,
    isEnabled: true,
    icon: "💊",
    recommendedBy: ["Huberman", "Attia"],
    evidenceNote:
      "Magnesium L-threonate (Magtein) has been shown to increase brain magnesium levels and improve sleep quality markers. Bisglycinate is well-absorbed and less likely to cause GI distress than other forms.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-010",
    pillar: "sleep",
    name: "Wind-Down Routine",
    description:
      "Reading, stretching, breathing exercises, or journaling. Offloads cognitive load and activates the parasympathetic nervous system for sleep readiness.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: -15,
    timeOfDay: "night",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 10,
    isEnabled: true,
    icon: "🧘",
    recommendedBy: ["Walker"],
    evidenceNote:
      "A consistent pre-sleep routine serves as a conditioned cue for the brain to begin the physiological wind-down process. Journaling specifically reduces pre-sleep cognitive arousal by externalizing rumination.",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sleep-default-011",
    pillar: "sleep",
    name: "Lights Out",
    description:
      "Consistent bedtime every night, including weekends. Anchors your circadian rhythm and maximizes alignment of sleep-dependent hormonal processes.",
    source: "default",
    timingAnchor: "bed",
    timingOffsetMinutes: 0,
    timeOfDay: "night",
    daysActive: [true, true, true, true, true, true, true],
    sortOrder: 11,
    isEnabled: true,
    icon: "😴",
    recommendedBy: ["Walker", "Huberman", "Attia"],
    evidenceNote:
      "Irregular sleep timing (social jet lag) disrupts the master clock and is associated with metabolic dysfunction independent of total sleep duration. Consistency is as important as duration.",
    createdAt: "2026-01-01T00:00:00Z",
  },
];
