import { MealIdea } from "./types";

export const meals: MealIdea[] = [
  // === BREAKFAST ===
  {
    id: "meal-001",
    name: "Greek Yogurt + Chia + Berries",
    type: "breakfast",
    ingredients: [
      "300g Greek yogurt",
      "1 tbsp chia seeds",
      "30g mixed berries",
      "1 boiled egg",
      "Cucumber & tomato on the side",
    ],
    macros: { calories: 430, protein: 40, carbs: 25, fat: 18, fiber: 15 },
    tags: ["high-protein", "gut-health", "quick"],
    tier: "free",
  },
  {
    id: "meal-002",
    name: "Veggie Omelet + Avocado",
    type: "breakfast",
    ingredients: [
      "3 eggs",
      "Handful of spinach",
      "1/4 avocado",
      "Cherry tomatoes",
      "1 tsp olive oil",
    ],
    macros: { calories: 420, protein: 25, carbs: 8, fat: 32, fiber: 6 },
    tags: ["low-carb", "keto-friendly", "quick"],
    tier: "free",
  },
  {
    id: "meal-003",
    name: "Overnight Oats + Protein",
    type: "breakfast",
    ingredients: [
      "60g rolled oats",
      "1 scoop whey protein",
      "200ml almond milk",
      "1 tbsp pumpkin seeds",
      "Blueberries",
    ],
    macros: { calories: 450, protein: 35, carbs: 48, fat: 12, fiber: 8 },
    tags: ["meal-prep", "high-protein", "carb-backload"],
    tier: "premium",
  },

  // === LUNCH ===
  {
    id: "meal-004",
    name: "Chicken + Rice + Veggies",
    type: "lunch",
    ingredients: [
      "150g chicken breast",
      "200g white rice",
      "Broccoli & carrots",
      "1 tsp olive oil",
      "Seasoning of choice",
    ],
    macros: { calories: 550, protein: 45, carbs: 60, fat: 12, fiber: 6 },
    tags: ["classic", "meal-prep", "balanced"],
    tier: "free",
  },
  {
    id: "meal-005",
    name: "Salmon + Sweet Potato + Greens",
    type: "lunch",
    ingredients: [
      "150g salmon fillet",
      "200g sweet potato",
      "Mixed salad greens",
      "Lemon & olive oil dressing",
    ],
    macros: { calories: 580, protein: 40, carbs: 45, fat: 24, fiber: 8 },
    tags: ["omega-3", "anti-inflammatory"],
    tier: "free",
  },
  {
    id: "meal-006",
    name: "Cod + Eggs + Avocado",
    type: "lunch",
    ingredients: [
      "120g cod fillet",
      "2 boiled eggs",
      "1/2 avocado",
      "Steamed broccoli",
    ],
    macros: { calories: 480, protein: 45, carbs: 8, fat: 30, fiber: 8 },
    tags: ["low-carb", "high-protein"],
    tier: "premium",
  },

  // === DINNER ===
  {
    id: "meal-007",
    name: "Beef + Sweet Potato + Cauliflower",
    type: "dinner",
    ingredients: [
      "150g lean beef steak",
      "250g sweet potato wedges",
      "Roasted cauliflower",
      "Seasoning",
    ],
    macros: { calories: 620, protein: 45, carbs: 55, fat: 22, fiber: 8 },
    tags: ["carb-backload", "high-protein", "satisfying"],
    tier: "free",
  },
  {
    id: "meal-008",
    name: "Turkey Stir-Fry + Brown Rice",
    type: "dinner",
    ingredients: [
      "150g ground turkey",
      "Mixed stir-fry vegetables",
      "200g brown rice",
      "Soy sauce & ginger",
    ],
    macros: { calories: 560, protein: 40, carbs: 58, fat: 16, fiber: 6 },
    tags: ["quick", "balanced", "carb-backload"],
    tier: "premium",
  },
  {
    id: "meal-009",
    name: "Lean Chicken + Quinoa Bowl",
    type: "dinner",
    ingredients: [
      "150g chicken breast",
      "150g quinoa",
      "Roasted vegetables",
      "Tahini drizzle",
    ],
    macros: { calories: 540, protein: 48, carbs: 50, fat: 14, fiber: 8 },
    tags: ["balanced", "meal-prep"],
    tier: "premium",
  },

  // === SNACKS ===
  {
    id: "meal-010",
    name: "Cottage Cheese + Pumpkin Seeds + Celery",
    type: "snack",
    ingredients: [
      "150g cottage cheese",
      "30g pumpkin seeds",
      "Celery sticks",
    ],
    macros: { calories: 250, protein: 24, carbs: 7, fat: 14, fiber: 5 },
    tags: ["high-protein", "low-carb", "quick"],
    tier: "free",
  },
  {
    id: "meal-011",
    name: "Apple + Almond Butter",
    type: "snack",
    ingredients: ["1 medium apple", "2 tbsp almond butter"],
    macros: { calories: 280, protein: 7, carbs: 30, fat: 16, fiber: 6 },
    tags: ["quick", "satisfying"],
    tier: "free",
  },
  {
    id: "meal-012",
    name: "Protein Shake + Banana",
    type: "snack",
    ingredients: [
      "1 scoop whey protein",
      "1 banana",
      "200ml water or milk",
    ],
    macros: { calories: 280, protein: 30, carbs: 32, fat: 3, fiber: 3 },
    tags: ["post-workout", "quick", "high-protein"],
    tier: "premium",
  },

  // === DESSERT ===
  {
    id: "meal-013",
    name: "Cottage Cheese + Pumpkin Seeds + Berries",
    type: "dessert",
    ingredients: [
      "100g cottage cheese",
      "30g pumpkin seeds",
      "50g mixed berries",
    ],
    macros: { calories: 220, protein: 18, carbs: 12, fat: 11, fiber: 4 },
    tags: ["high-protein", "guilt-free", "quick"],
    tier: "free",
  },
  {
    id: "meal-014",
    name: "Dark Chocolate + Walnuts",
    type: "dessert",
    ingredients: ["20g dark chocolate (85%+)", "15g walnuts"],
    macros: { calories: 200, protein: 4, carbs: 10, fat: 16, fiber: 3 },
    tags: ["antioxidant", "satisfying"],
    tier: "premium",
  },
];
