import type { MetadataRoute } from "next";

/**
 * PWA manifest — the single source of truth that browsers/OSes read
 * to decide how to install and present the app. Generated by Next.js
 * at /manifest.webmanifest.
 *
 * Tuning notes:
 *  - display: "standalone" — opens full-screen without browser chrome
 *    once installed. iOS honors this only when launched from Home
 *    Screen; Safari tabs still show as a regular page.
 *  - scope: "/" — every route under our origin counts as "in the app."
 *    A user who taps an external link doesn't stay trapped in our
 *    standalone window.
 *  - start_url: "/today" — opens straight to the daily timeline, the
 *    fastest path to value. Includes ?source=pwa so we can later tell
 *    PWA launches from raw-URL visits in analytics.
 *  - icons: 192 + 512 PNG (manifest requires both sizes minimum),
 *    plus matching maskable variants for Android adaptive shapes
 *    (circle, squircle, rounded square — the OS picks).
 *  - shortcuts: 4 quick actions that show up when the user long-
 *    presses our icon on Android (and in some app launchers).
 *  - categories: helps Chrome's app drawer + app store-style
 *    discovery surfaces classify us.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Protocolize — Longevity Intelligence",
    short_name: "Protocolize",
    description:
      "Your adaptive daily protocol. Track behaviors, biomarkers, and the calm intelligence layer that shapes your longevity routine.",
    start_url: "/today?source=pwa",
    scope: "/",
    id: "/?app=protocolize",
    display: "standalone",
    display_override: ["window-controls-overlay", "standalone"],
    background_color: "#F6F7F9",
    theme_color: "#F6F7F9",
    orientation: "portrait",
    lang: "en",
    dir: "ltr",
    categories: ["health", "lifestyle", "productivity", "medical"],
    prefer_related_applications: false,
    icons: [
      // Standard "any" icons — used by Chrome's app drawer + iOS home
      // screen + the bookmark/tab icon dance. Multiple sizes so the OS
      // picks the optimal one for its display density.
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Maskable icons — Android applies its own mask shape (circle,
      // squircle, rounded square) over these. The artwork has built-in
      // safe-area padding (~80%) so the shape doesn't clip the design.
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Today",
        short_name: "Today",
        description: "Jump to your daily timeline",
        url: "/today?source=shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Insights",
        short_name: "Insights",
        description: "Patterns from your data",
        url: "/insights?source=shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Body Trends",
        short_name: "Body",
        description: "Log or review body trends",
        url: "/biomarkers?source=shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Library",
        short_name: "Library",
        description: "Discover protocol packs",
        url: "/library?source=shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
    ],
    // Web Share Target — lets other apps share content TO Protocolize.
    // When the user picks Protocolize from their OS share sheet, the
    // shared text/url/title lands on /share via GET parameters; the
    // page then offers to file it as a note attached to a biomarker
    // entry or as a custom behavior reminder.
    //
    // The cast is because Next's typed Manifest doesn't include
    // share_target yet — but every browser that honors the field
    // accepts this exact shape (per the W3C spec).
    share_target: {
      action: "/share",
      method: "GET",
      params: {
        title: "title",
        text: "text",
        url: "url",
      },
    },
    // Type assertion: Next's MetadataRoute.Manifest type lags behind
    // the W3C spec for share_target. The shape above is valid HTML5.
  } as MetadataRoute.Manifest;
}
